package common

import "time"

const (
	APPNAME                   = "cropdroid"
	DISPLAYNAME               = "CropDroid™"
	PACKAGE                   = "com.jeremyhahn.cropdroid"
	TIME_FORMAT               = time.RFC3339
	TIME_FORMAT_LOCAL         = "2006-01-02T15:04:05Z"
	TIME_DISPLAY_FORMAT       = "01-02-2006 15:04:05 MST"
	TIME_RFC1123_FORMAT       = "Mon, 02 Jan 2006 15:04:05 MST"
	TIME_NULL                 = "0001-01-01 00:00:00+00:00"
	BUFFERED_CHANNEL_SIZE     = 256
	WEBSOCKET_KEEPALIVE       = 10 * time.Second
	HTTP_CLIENT_TIMEOUT       = 10 * time.Second
	HTTP_SERVER_READ_TIMEOUT  = 5 * time.Second
	HTTP_SERVER_WRITE_TIMEOUT = 10 * time.Second
	HTTP_SERVER_IDLE_TIMEOUT  = 120 * time.Second
	HTTP_PUBLIC_HTML          = "public_html"
	SWITCH_OFF                = 0
	SWITCH_ON                 = 1
	//FARM_MAX_SIZE         = 10000
	HOURS_IN_A_YEAR                    = 8766
	DEFAULT_FARM_CONFIG_HISTORY_LENGTH = 5

	DATATYPE_FLOAT  = 0
	DATATYPE_INT    = 1
	DATATYPE_STRING = 2

	NOTIFICATION_PRIORITY_LOW  = 0
	NOTIFICATION_PRIORITY_MED  = 1
	NOTIFICATION_PRIORITY_HIGH = 2

	// IDs of devices as inserted by dao.Initializer
	CONTROLLER_TYPE_ID_SERVER    = 1
	CONTROLLER_TYPE_ID_ROOM      = 2
	CONTROLLER_TYPE_ID_RESERVOIR = 3
	CONTROLLER_TYPE_ID_DOSER     = 4

	CONTROLLER_TYPE_ROOM      = "room"
	CONTROLLER_TYPE_DOSER     = "doser"
	CONTROLLER_TYPE_RESERVOIR = "reservoir"
	CONTROLLER_TYPE_SERVER    = "server"

	CONFIG_NAME_KEY     = "name"
	CONFIG_INTERVAL_KEY = "interval"
	CONFIG_TIMEZONE_KEY = "timezone"
	CONFIG_MODE_KEY     = "mode"

	CONFIG_SMTP_ENABLE_KEY    = "smtp.enable"
	CONFIG_SMTP_HOST_KEY      = "smtp.host"
	CONFIG_SMTP_PORT_KEY      = "smtp.port"
	CONFIG_SMTP_USERNAME_KEY  = "smtp.username"
	CONFIG_SMTP_PASSWORD_KEY  = "smtp.password"
	CONFIG_SMTP_RECIPIENT_KEY = "smtp.recipient"

	CONFIG_MODE_VIRTUAL     = "virtual"
	CONFIG_MODE_SERVER      = "server"
	CONFIG_MODE_CLOUD       = "cloud"
	CONFIG_MODE_MAINTENANCE = "maintenance"

	SCHEDULE_FREQUENCY_DOES_NOT_REPEAT = 0
	SCHEDULE_FREQUENCY_DAILY           = 1
	SCHEDULE_FREQUENCY_WEEKLY          = 2
	SCHEDULE_FREQUENCY_MONTHLY         = 3
	SCHEDULE_FREQUENCY_YEARLY          = 4

	ALGORITHM_PH_ID  = 1
	ALGORITHM_ORP_ID = 2

	MODE_STANDALONE = "standalone"
	MODE_CLUSTER    = "cluster"
	MODE_CLOUD      = "cloud"

	DEFAULT_USER     = "admin"
	DEFAULT_PASSWORD = "cropdroid"
	DEFAULT_ROLE     = "admin"

	AUTH_TYPE_LOCAL  = 0
	AUTH_TYPE_GOOGLE = 1

	// Initializer / provisioner
	DEFAULT_GALLONS = "50"

	CONFIG_ROOM_ENABLE_KEY = "room.enable"
	CONFIG_ROOM_NOTIFY_KEY = "room.notify"
	CONFIG_ROOM_URI_KEY    = "room.uri"
	CONFIG_ROOM_VIDEO_KEY  = "room.video"

	CONFIG_RESERVOIR_ENABLE_KEY             = "reservoir.enable"
	CONFIG_RESERVOIR_NOTIFY_KEY             = "reservoir.notify"
	CONFIG_RESERVOIR_URI_KEY                = "reservoir.uri"
	CONFIG_RESERVOIR_GALLONS_KEY            = "reservoir.gallons"
	CONFIG_RESERVOIR_TARGET_TEMP_KEY        = "reservoir.targetTemp"
	CONFIG_RESERVOIR_WATERCHANGE_ENABLE_KEY = "reservoir.waterchange.enable"
	CONFIG_RESERVOIR_WATERCHANGE_NOTIFY_KEY = "reservoir.waterchange.notify"

	CONFIG_DOSER_ENABLE_KEY    = "doser.enable"
	CONFIG_DOSER_NOTIFY_KEY    = "doser.notify"
	CONFIG_DOSER_URI_KEY       = "doser.uri"
	CONFIG_DOSER_GALLONS_KEY   = "doser.gallons"
	CONFIG_DOSER_CHANNEL_COUNT = 15

	METRIC_ROOM_MEMORY_KEY     = "mem"
	METRIC_ROOM_TEMPF0_KEY     = "tempF0"
	METRIC_ROOM_TEMPC0_KEY     = "tempC0"
	METRIC_ROOM_HUMIDITY0_KEY  = "humidity0"
	METRIC_ROOM_HEATINDEX0_KEY = "heatIndex0"
	METRIC_ROOM_TEMPF1_KEY     = "tempF1"
	METRIC_ROOM_TEMPC1_KEY     = "tempC1"
	METRIC_ROOM_HUMIDITY1_KEY  = "humidity1"
	METRIC_ROOM_HEATINDEX1_KEY = "heatIndex1"
	METRIC_ROOM_TEMPF2_KEY     = "tempF2"
	METRIC_ROOM_TEMPC2_KEY     = "tempC2"
	METRIC_ROOM_HUMIDITY2_KEY  = "humidity2"
	METRIC_ROOM_HEATINDEX2_KEY = "heatIndex2"
	METRIC_ROOM_WATERTEMP0_KEY = "water0"
	METRIC_ROOM_WATERTEMP1_KEY = "water1"
	METRIC_ROOM_VPD_KEY        = "vpd"
	METRIC_ROOM_CO2_KEY        = "co2"
	METRIC_ROOM_PHOTO_KEY      = "photo"
	METRIC_ROOM_WATERLEAK0_KEY = "leak0"
	METRIC_ROOM_WATERLEAK1_KEY = "leak1"

	METRIC_RESERVOIR_MEMORY_KEY       = "mem"
	METRIC_RESERVOIR_TEMP_KEY         = "resTemp"
	METRIC_RESERVOIR_PH_KEY           = "PH"
	METRIC_RESERVOIR_EC_KEY           = "EC"
	METRIC_RESERVOIR_TDS_KEY          = "TDS"
	METRIC_RESERVOIR_ORP_KEY          = "ORP"
	METRIC_RESERVOIR_DOMGL_KEY        = "DO_mgL"
	METRIC_RESERVOIR_DOPER_KEY        = "DO_PER"
	METRIC_RESERVOIR_SAL_KEY          = "SAL"
	METRIC_RESERVOIR_SG_KEY           = "SG"
	METRIC_RESERVOIR_ENVTEMP_KEY      = "envTemp"
	METRIC_RESERVOIR_ENVHUMIDITY_KEY  = "envHumidity"
	METRIC_RESERVOIR_ENVHEATINDEX_KEY = "envHeatIndex"
	METRIC_RESERVOIR_LOWERFLOAT_KEY   = "lowerFloat"
	METRIC_RESERVOIR_UPPERFLOAT_KEY   = "upperFloat"

	CHANNEL_ROOM_LIGHTING       = "Lighting"
	CHANNEL_ROOM_LIGHTING_ID    = 0
	CHANNEL_ROOM_AC             = "Air Conditioner"
	CHANNEL_ROOM_AC_ID          = 1
	CHANNEL_ROOM_HEATER         = "Heater"
	CHANNEL_ROOM_HEATER_ID      = 2
	CHANNEL_ROOM_DEHUEY         = "Dehumidifier"
	CHANNEL_ROOM_DEHUEY_ID      = 3
	CHANNEL_ROOM_VENTILATION    = "Ventilation"
	CHANNEL_ROOM_VENTILATION_ID = 4
	CHANNEL_ROOM_CO2            = "Co2"
	CHANNEL_ROOM_CO2_ID         = 5

	CHANNEL_RESERVOIR_DRAIN        = "Drain"
	CHANNEL_RESERVOIR_DRAIN_ID     = 0
	CHANNEL_RESERVOIR_CHILLER      = "Chiller"
	CHANNEL_RESERVOIR_CHILLER_ID   = 1
	CHANNEL_RESERVOIR_HEATER       = "Heater"
	CHANNEL_RESERVOIR_HEATER_ID    = 2
	CHANNEL_RESERVOIR_POWERHEAD    = "Powerhead"
	CHANNEL_RESERVOIR_POWERHEAD_ID = 3
	CHANNEL_RESERVOIR_AUX          = "Auxiliary"
	CHANNEL_RESERVOIR_AUX_ID       = 4
	CHANNEL_RESERVOIR_TOPOFF       = "Top-off"
	CHANNEL_RESERVOIR_TOPOFF_ID    = 5
	CHANNEL_RESERVOIR_FAUCET       = "Faucet"
	CHANNEL_RESERVOIR_FAUCET_ID    = 6

	CHANNEL_DOSER_PHDOWN      = "pH DOWN"
	CHANNEL_DOSER_PHDOWN_ID   = 0
	CHANNEL_DOSER_PHUP        = "pH UP"
	CHANNEL_DOSER_PHUP_ID     = 1
	CHANNEL_DOSER_OXIDIZER    = "Oxidizer"
	CHANNEL_DOSER_OXIDIZER_ID = 2
	CHANNEL_DOSER_TOPOFF      = "Top-off"
	CHANNEL_DOSER_TOPOFF_ID   = 3
	CHANNEL_DOSER_NUTE1       = "Nutrient Part 1"
	CHANNEL_DOSER_NUTE1_ID    = 4
	CHANNEL_DOSER_NUTE2       = "Nutrient Part 2"
	CHANNEL_DOSER_NUTE2_ID    = 5
	CHANNEL_DOSER_NUTE3       = "Nutrient Part 3"
	CHANNEL_DOSER_NUTE3_ID    = 6
	// end initializer / provisioner
)
