// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://www.cropdroid.com/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://www.cropdroid.com/support",
            "email": "support@cropdroid.com"
        },
        "license": {
            "name": "GNU AFFERO GENERAL PUBLIC LICENSE",
            "url": "https://www.gnu.org/licenses/agpl-3.0.txt"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/shoppingcart": {
            "get": {
                "description": "Returns a list of products from the merchange provider / credit card processor",
                "produces": [
                    "application/json"
                ],
                "summary": "GetProducts",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v0.0.3",
	Host:             "www.cropdroid.com",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "CropDroid REST API",
	Description:      "This is the RESTful web servce for CropDroid.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
